name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: {% raw %} ${{ secrets.DIGITAL_OCEAN_TOKEN }} {% endraw %}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Build image
        run: DOCKER_BUILDKIT=1 docker build -t registry.digitalocean.com/cunybpl/{{ cookiecutter.project_slug }}:{{ '${{github.event.inputs.version }}' }} .

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/cunybpl/{{ cookiecutter.project_slug }}:{{ '${{github.event.inputs.version }}' }}
